### ISSUE TITLE
cube_masking_remove

### ISSUE THREAD

**Issue by jcauzid** [hameye/MARCIA#10]
Serait-il possible d'utiliser cube_masking_remove() sur les mixtes et les non-indexés?
Ca permettrait de créer de nouveaux cubes de données sans ces pixels et de passer les données vers des logiciels de cartographie quantitative après un tri des pixels non-attribuables à un minéral ou à un autre.

**Comment by hameye** [comment]
@jcauzid J'essaie de faire cela rapidement, ca ne doit pas etre trop dur.

**Comment by jcauzid** [comment]
Et les non-indexés aussi, ce serait possible?

**Comment by hameye** [comment]
@jcauzid Je te laisse vérifier en installant la branche dev et en faisant le test 

```pip install git+ssh://git@github.com/hameye/MARCIA.git@dev```

Pour les mixed il suffit de faire cube_masking_remove("mixed")
Pour les non indexes : cube_masking_remove("not indexed")

Si c'est convenable je mettrai a jour sur la version stable
