### ISSUE TITLE
mask export

### ISSUE THREAD

**Issue by jcauzid** [hameye/MARCIA#11]
Hello,
When exporting the mask, the result is an image of the mask, not the mask itself: we have axes and title. Would it be possible to also export the mask itself, ie an image holding only zeros and ones which could be used for merging and calculating things in an imaging soft?  Maybe that could be done with an extra argument on the save_mask function, default as it is now and mask itself with a boolean given afterwards?

We need that in order to keep the signal from a series of minerals only, applied to images, not the raw datacube that will be afterwards used in XMapTools. XMapTools cannot manage the datacube.

Best regards,
Jean

**Comment by hameye** [comment]
@jcauzid 
Hi Jean, this does not seem to be a lot of work, I might have done by the end of the weekend. I let you know when this is done. I probably will update the version on pypy in the same time. 

Thank you,

Hadrien
